### ISSUE TITLE
could we automatic generate corresponding points in source and target image?

### ISSUE THREAD

**Issue by KakaVlasic** [ycjungSubhuman/python-warp-ui#1]
Hi! Thanks for sharing, how could we get corresponding points in a automatic way?

**Comment by ycjungSubhuman** [comment]
Automatically finding feature points in a photo is relatively easy. You can check out this repo: https://github.com/microsoft/Deep3DFaceReconstruction. Also, there are many codes and papers available for the detection of facial landmarks from photos. However, finding feature points in a warped image such as cartoon images is not solved completely. It is quite a challenging problem. Still, there are some papers and codes that tackle this problem: i.e. https://github.com/papulke/face-of-art.

Good luck.
Yucheol.

**Comment by ycjungSubhuman** [comment]
Since finding the points automatically is not the main concern of this project, closing the issue.
